---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:54
---
-- batchGetRiskUserScript RedisRuleCacheService
local key = KEYS[1]
local ruleList = {}
local ruleStr
for _, value in pairs(ARGV) do
    ruleStr = tostring(redis.call('GET', key .. value))
    if ruleStr then
        table.insert(ruleList, cjson.decode(ruleStr))
    end
end
if not next(ruleList) then
    return nil
else
    return cjson.encode(ruleList)
end