---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 11:02
---
-- batchGetRuleScript RuleCacheService
local key = KEYS[1]
local rule
local goodsId
for _ , ruleData in pairs(ARGV) do
    rule = cjson.decode(ruleData)
    goodsId = rule['goodsId']
    local id = rule['id']
    redis.call('HSET' , key .. goodsId , '@type' , 'com.waibao.rcde.entity.Rule')
    for index , value in pairs(rule) do
        redis.call('HSET' , key .. goodsId , index , value)
    end
end