---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:58
---
-- batchGetRule RuleCacheService
local key = KEYS[1]
local rule
local goodsId
local ruleList = {}
for _ , ruleData in pairs(ARGV) do
    rule = cjson.decode(ruleData)
    goodsId = rule['goodsId']
    local ruleKeys = redis.call('HKEYS' , key .. goodsId)
    if next(ruleKeys) then
        for _ , value in pairs(ruleKeys) do
            rule[value] = redis.call('HGET' , key .. goodsId , tostring(value))
        end
        table.insert(ruleList , rule)
    end
end

return cjson.encode(ruleList)