---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:53
---
-- batchInsertRiskUserScript RiskUserCacheService
local key = KEYS[1]
local jsonStr = string.gsub(ARGV[1] , '("userId":)(%s*)(%d+)' , '%1"%3"')
for _ , riskUserVO in pairs(cjson.decode(jsonStr)) do
    redis.call('SADD' , key .. riskUserVO["goodsId"] , riskUserVO["userId"])
end