---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:53
---
-- batchInsertRiskUserScript RiskUserCacheService
local key = KEYS[1]
local ruleList = {}
local rule
for _ , value in pairs(ARGV) do
    rule = cjson.decode(value)
    rule['@type'] = 'com.waibao.rcde.entity.Rule'
    local count = tonumber(redis.call('SET' , key .. rule["id"] , cjson.encode(rule)))
    if count == 0 then
        table.insert(ruleList , rule)
    else
        redis.call('SET' , key .. rule["goodsId"] , cjson.encode(rule))
    end
end
if not next(ruleList) then
    return nil
else
    return cjson.encode(ruleList)
end