---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 11:02
---
-- batchGetDepositScript DepositCacheService
local key = KEYS[1]
local deposit
local userId
for _ , depositData in pairs(ARGV) do
    deposit = cjson.decode(depositData)
    userId = deposit['userId']
    local id = deposit['id']
    redis.call('SADD' , 'index-' .. key .. userId , id)
    redis.call('HSET' , key .. id , '@type' , 'com.waibao.rcde.entity.Deposit')
    for index , value in pairs(deposit) do
        redis.call('HSET' , key .. id , index , value)
    end
end