---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:53
---
-- batchCheckUserScript RiskUserCacheService
local key = KEYS[1]
local riskUserVOList = {}
local jsonStr = string.gsub(ARGV[1] , '("userId":)(%s*)(%d+)' , '%1"%3"')
for _ , riskUserVO in pairs(cjson.decode(jsonStr)) do
    local count = tonumber(redis.call('SISMEMBER' , key .. riskUserVO["goodsId"] , riskUserVO["userId"]))
    if count == 1 then
        table.insert(riskUserVOList , riskUserVO)
    end
end

return cjson.encode(riskUserVOList)