---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:55
---
-- getDepositScript DepositCacheService
local key = KEYS[1]
local deposit = {}
local depositList = {}
local userId = ARGV[1]
local depositIds = redis.call('SMEMBERS' , 'index-' .. key .. userId)
for _ , depositId in ipairs(depositIds) do
    local depositKeys = redis.call('HVALS' , key .. depositId)
    if next(depositKeys) then
        for _ , value in pairs(depositKeys) do
            deposit[value] = redis.call('HGET' , key .. depositId , value)
        end
        table.insert(depositList , deposit)
    end
end

return cjson.encode(depositList)