---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:55
---
-- getRuleScript RuleCacheService
local key = KEYS[1]
local rule = {}
local ruleList = {}
local goodsId = ARGV[1]
local ruleKeys = redis.call('HVALS' , key .. goodsId)
if next(ruleKeys) then
    for _ , value in pairs(ruleKeys) do
        rule[value] = redis.call('HGET' , key .. goodsId , value)
    end
    table.insert(ruleList , rule)
end

return cjson.encode(ruleList)