---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:56
---
-- insertDepositScript DepositCacheService
local key = KEYS[1]
local jsonStr = string.gsub(ARGV[1] , '("userId":)(%s*)(%d+)' , '%1"%3"')
local deposit = cjson.decode(jsonStr)
local userId = deposit['userId']
local id = deposit['id']
redis.call('SADD' , 'index-' .. key .. userId , id)
for index , value in pairs(deposit) do
    redis.call('HSET' , key .. id , index , tostring(value))
end