---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:56
---
-- insertDepositScript DepositCacheService
local key = KEYS[1]
local deposit = cjson.decode(ARGV[1])
local userId = deposit['userId']
local id = deposit['id']
redis.call('SADD' , 'index-' .. key .. userId , id)
redis.call('HSET' , key .. id , '@type' , 'com.waibao.rcde.entity.Deposit')
for index , value in pairs(deposit) do
    redis.call('HSET' , key .. id , index , value)
end