---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:56
---
-- insertRuleScript RuleCacheService
local key = KEYS[1]
local rule = cjson.decode(ARGV[1])
local goodsId = rule['goodsId']
for index , value in pairs(rule) do
    redis.call('HSET' , key .. goodsId , index , tostring(value))
end