---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:25
---
-- batchDecreasePurchasedScript PurchasedUserCacheService

local key = KEYS[1]
local orderVOList = {}
local goodsId
local userId
local orderVO
local count
for _ , value in pairs(ARGV) do
    orderVO = cjson.decode(value)
    goodsId = orderVO['goodsId']
    userId = orderVO['userId']
    count = orderVO['count']
    if tonumber(redis.call('HEXISTS' , key .. goodsId , userId)) == 0 then
        table.insert(orderVOList , orderVO)
    else
        local current = tonumber(redis.call('HINCRBY' , key .. goodsId , userId , -count))
        if current <= 0 then
            redis.call('HDEL' , key .. goodsId , userId)
        end
    end
end

return cjson.encode(orderVOList)