---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:09
---
-- batchRollBackGoodsStorage SeckillGoodsCacheService
local key = KEYS[1]
local orderVOList = {}
local goodsId
for _ , orderVO in pairs(cjson.decode(ARGV[1])) do
    goodsId = tostring(orderVO['goodsId'])
    if not redis.call('HGET' , key .. goodsId , 'storage') then
        orderVO['status'] = '库存回滚失败'
        table.insert(orderVOList , orderVO)
    else
        redis.call('HINCRBY' , key .. goodsId , 'storage' , tonumber(orderVO['count']))
    end
end

return cjson.encode(orderVOList)