---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 09:52
---
-- batchInsertGoodsScript SeckillGoodsCacheService
local key = KEYS[1]
local goodsId
for _ , seckillGoods in pairs(cjson.decode(ARGV[1])) do
    goodsId = tostring(seckillGoods['goodsId'])
    for index , value in pairs(seckillGoods) do
        redis.call('HSET' , key .. goodsId , index , tostring(value))
    end
end