---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:10
---
-- batchInsertGoodsRetailerScript GoodsRetailerCacheService
local key = KEYS[1]
local retailerId
local goodsId
for _ , seckillGoods in pairs(cjson.decode(ARGV[1])) do
    goodsId = tostring(seckillGoods['goodsId'])
    retailerId = tostring(seckillGoods['retailerId'])
    for index , value in pairs(seckillGoods) do
        redis.call('HSET' , key .. retailerId .. '-' .. goodsId , index , tostring(value))
    end
end