---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/18 23:29
---
-- canalSyncLogUserCreditScript LogUserCreditCacheService
local key = KEYS[1]
local result = {}
local startPos
for _ , value in pairs(redis.call('SPOP' , key , 500)) do
    startPos , _ = string.find(value , '-paid')
    if startPos then
        result[string.sub(value , 1 , startPos - 1)] = 'paid'
    else
        redis.call('SADD' , key , value)
    end
end

return cjson.encode(result)