---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:10
---
-- batchInsertGoodsRetailerScript GoodsRetailerCacheService
local key = KEYS[1]
local retailerId
local seckillGoods
local goodsId
for _ , seckillGoodsData in pairs(ARGV) do
    seckillGoods = cjson.decode(seckillGoodsData)
    goodsId = seckillGoods['goodsId']
    retailerId = seckillGoods['retailerId']
    redis.call('HSET' , key .. retailerId .. '-' .. goodsId , '@type' , 'com.waibao.seckill.entity.SeckillGoods')
    for index , value in pairs(seckillGoods) do
        redis.call('HSET' , key .. retailerId .. '-' .. goodsId , index , value)
    end
end