---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:22
---
-- batchGetLogGoodsScript LogSeckillGoodsCacheService
local key = KEYS[1]
local orderVO
local orderVOList = {}
local goodsId
for _ , value in pairs(ARGV) do
    orderVO = cjson.decode(value)
    key = '"' .. string.gsub(key , '"' , '') .. goodsId .. '"'
    if tonumber(redis.call('LREM' , key , 0 , orderVO['orderId'] .. '-' .. 'CANCEL')) > 0 then
        redis.call('LPUSH' , key , 0 , orderVO['orderId'] .. '-' .. 'CANCEL')
        table.insert(orderVOList , orderVO)
    end
end

if not next(orderVOList) then
    return nil
else
    return cjson.encode(orderVOList)
end