---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 09:52
---
-- batchInsertGoodsScript GoodsCacheService
local key = KEYS[1]
local seckillGoodsList = {}
local seckillGoods
local goodsId
for _ , seckillGoodsData in pairs(ARGV) do
    seckillGoods = cjson.decode(seckillGoodsData)
    goodsId = seckillGoods['goodsId']
    if next(redis.call('HKEYS' , key .. goodsId)) then
        table.insert(seckillGoodsList , seckillGoods)
    else
        redis.call('HSET' , key .. goodsId , '@type' , 'com.waibao.seckill.entity.SeckillGoods')
        for index , value in pairs(seckillGoods) do
            redis.call('HSET' , key .. goodsId , index , value)
        end
    end
end

if not next(seckillGoodsList) then
    return nil
else
    return cjson.encode(seckillGoodsList)
end