---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 09:52
---
-- batchInsertGoodsScript GoodsCacheService
local key = KEYS[1]
local seckillGoods
local goodsId
for _ , seckillGoodsData in pairs(ARGV) do
    seckillGoods = cjson.decode(seckillGoodsData)
    goodsId = seckillGoods['goodsId']
    redis.call('HSET' , key .. goodsId , '@type' , 'com.waibao.seckill.entity.SeckillGoods')
    for index , value in pairs(seckillGoods) do
        redis.call('HSET' , key .. goodsId , index , value)
    end
end