---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 09:57
---
-- canalSyncGoodsScript SeckillGoodsCacheService
local key = KEYS[1]
local seckillGoods
local goodsId
for _ , redisCommand in pairs(cjson.decode(ARGV[1])) do
    seckillGoods = redisCommand['value']
    goodsId = tostring(seckillGoods['goodsId'])
    if (redisCommand['command'] == 'INSERT' or redisCommand['command'] == 'UPDATE') then
        for index , value in pairs(seckillGoods) do
            redis.call('HSET' , key .. goodsId , index , tostring(value))
        end
    else
        redis.call('DEL' , key)
    end
end