---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 09:57
---
-- canalSyncGoodsScript GoodsCacheService
local key = KEYS[1]
local redisCommand
local seckillGoods
local goodsId
for _ , redisCommandData in pairs(ARGV) do
    redisCommand = cjson.decode(redisCommandData)
    seckillGoods = redisCommand['value']
    goodsId = seckillGoods['goodsId']
    if (redisCommand['command'] == 'INSERT' or redisCommand['command'] == 'UPDATE') then
        redis.call('HSET' , key .. goodsId , '@type' , 'com.waibao.seckill.entity.SeckillGoods')
        for index , value in pairs(seckillGoods) do
            redis.call('HSET' , key .. goodsId , index , value)
        end
    else
        redis.call('DEL' , key)
    end
end