---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:21
---
-- decreaseGoodsRetailerStorage GoodsRetailerCacheService
local key = KEYS[1]
local retailerId = tostring(ARGV[1])
local goodsId = tostring(ARGV[2])
local count = tonumber(ARGV[3])
if tonumber(redis.call('HGET' , key .. retailerId .. goodsId , 'purchaseLimit')) < count then
    return false
end
if tonumber(redis.call('HINCRBY' , key .. retailerId .. goodsId , 'storage' , -count)) < 0 then
    redis.call('HINCRBY' , key .. goodsId , 'storage' , count)
    return false
else
    return true
end