---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:25
---
-- decreasePurchasedScript PurchasedUserCacheService
local key = KEYS[1]
local orderVOList = {}
for _, value in pairs(ARGV) do
    local orderVO = cjson.decode(value)
    key = '"' .. string.gsub(key, '"', '') .. orderVO['userId'] .. '"'
    local count = tonumber(redis.call('DECR', key))
    if count < 0 then
        redis.call('SET', key, 0)
        table.insert(orderVOList, orderVO)
    end
end
if not next(orderVOList) then
    return nil
else
    return cjson.encode(orderVOList)
end