---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:09
---
-- decreaseGoodsStorage GoodsCacheService
local key = KEYS[1]
local goodsId = ARGV[1]
local count = ARGV[2]
if tonumber(redis.call('HEGT', key .. goodsId, 'purchaseLimit')) < count then
    return false
end
if tonumber(redis.call('HINCRBY', key .. goodsId, 'storage', -count)) < 0 then
    redis.call('HINCRBY', key .. goodsId, 'storage', count)
    return false
else
    return true
end