---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:34
---
-- deleteSeckillPath SeckillPathCacheService
local key = KEYS[1]
local value = tonumber(ARGV[1])
local goodsId = tonumber(redis.call('GET' , key));
if (value == goodsId) then
    redis.call('DEL' , key)
    return true
else
    return false
end