---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:18
---
-- getGoodsRetailerScript GoodsRetailerCacheService
local key = KEYS[1]
local seckillGoods = {}
local retailerId = ARGV[1]
local goodsId = ARGV[2]
local seckillGoodsKeys = redis.call('HVALS', key .. retailerId .. goodsId)
for _, value in pairs(seckillGoodsKeys) do
    seckillGoods[value] = redis.call('HGET', key .. retailerId .. goodsId, value)
end

return cjson.encode(seckillGoods)