---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:46
---
-- increasePurchasedCountScript PurchasedUserCacheService
local key = KEYS[1]
local userId = tostring(ARGV[1])
local count = tonumber(ARGV[2])
local limit = tonumber(ARGV[3])

local currentCount = tonumber(redis.call('HINCRBY' , key , userId , count))
if (currentCount > limit) then
    redis.call('HINCRBY' , key , userId , -count)
    return -1
else
    return currentCount
end