---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:46
---
local key = KEYS[1]
local count = tonumber(ARGV[1])
local limit = tonumber(ARGV[2])
redis.call('INCRBY' , key , count)
local currentCount = tonumber(redis.call('GET' , key))
if (currentCount > limit) then
    redis.call('DECRBY' , key , count)
    return false
else
    return true
end