---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 09:55
---
-- insertGoodsScript GoodsCacheService
local key = KEYS[1]
local goodsId = seckillGoods['goodsId']
local seckillGoods = cjson.decode(ARGV[1])
redis.call('HSET' , key .. goodsId , '@type' , 'com.waibao.seckill.entity.SeckillGoods')
for index , value in pairs(seckillGoods) do
    redis.call('HSET' , key .. goodsId , index , value)
end