---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:13
---
-- insertGoodsRetailerScript GoodsRetailerCacheService
local key = KEYS[1]
local seckillGoods = cjson.decode(ARGV[1])
local retailerId = tostring(seckillGoods['retailerId'])
local goodsId = tostring(seckillGoods['goodsId'])
for index , value in pairs(seckillGoods) do
    redis.call('HSET' , key .. retailerId .. goodsId , index , tostring(value))
end
