---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 10:44
---
-- reachLimitScript PurchasedUserCacheService
local key = KEYS[1]
local limit = tonumber(ARGV[1])
local currentCount = tonumber(redis.call('GET' , key))
if (currentCount == nil) then
    return false
end
return (currentCount >= limit)