server:
  port: 33382

spring:
  application:
    name: waibao-order

  shardingsphere:
    datasource:
      names: master,slave,master-order-user,master-order-retailer,slave-order-user,slave-order-retailer
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://10.60.64.66:33306/waibao_v2?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://10.60.64.66:33307/waibao_v2?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001
      master-order-user:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://10.60.64.66:33306/waibao_order_user?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001
      master-order-retailer:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://10.60.64.66:33306/waibao_order_retailer?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001
      slave-order-user:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://10.60.64.66:33307/waibao_order_user?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001
      slave-order-retailer:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://10.60.64.66:33307/waibao_order_retailer?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001

    sharding:
      tables:
        admin:
          actualDataNodes: master.admin
        mq_msg_compensation:
          actualDataNodes: master.mq_msg_compensation
        log_order_goods:
          actualDataNodes: master.log_order_goods
        seckill_goods:
          actualDataNodes: master.seckill_goods
        order_user:
          actualDataNodes: master-order-user.order_user_$->{0..1}
          tableStrategy:
            inline:
              shardingColumn: user_id
              algorithmExpression: order_user_$->{user_id % 2}
        order_retailer:
          actualDataNodes: master-order-retailer.order_retailer_$->{0..1}
          tableStrategy:
            inline:
              shardingColumn: retailer_id
              algorithmExpression: order_retailer_$->{retailer_id % 2}

      master-slave-rules:
        master:
          master-data-source-name: master
          SlaveDataSourceNames: slave
        master-order-user:
          master-data-source-name: master-order-user
          SlaveDataSourceNames: slave-order-user
        master-order-retailer:
          master-data-source-name: master-order-retailer
          SlaveDataSourceNames: slave-order-retailer

  redis:
    host: 10.60.64.66
    password: wssy001
    timeout: 1000
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10

  task:
    execution:
      pool:
        max-size: 16
        keep-alive: "10s"
      thread-name-prefix: 异步任务-
    scheduling:
      pool:
        size: 5
      thread-name-prefix: 定时任务-

  cloud:
    nacos:
      server-addr: 10.60.64.66:8848
      discovery:
        namespace: waibao
      username: nacos
      password: nacos

      config:
        namespace: waibao
        extension-configs: application.properties,${spring.application.name}.properties

rocketmq:
  name-server: 10.60.64.66:39876
  producer:
    group: order-producer

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: enable
      logic-delete-value: false
      logic-not-delete-value: true
