---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/18 23:37
---
-- batchCheckLogPaymentOperationScript LogPaymentCacheService
local key = KEYS[1]
local operation = ARGV[2]
ARGV[1] = string.gsub(ARGV[1] , '("userId":)(%s*)(%d+)' , '%1"%3"')
local payId
local userId
local paymentVOList
for _ , paymentVO in pairs(cjson.decode(ARGV[1])) do
    payId = paymentVO['payId']
    userId = paymentVO['userId']
    if tonumber(redis.call('LREM' , key .. payId , 0 , userId .. '-' .. operation)) > 0 then
        redis.call('LPUSH' , key .. payId , 0 , userId .. '-' .. operation)
    else
        table.insert(paymentVOList , paymentVO)
    end
end

return cjson.encode(paymentVOList)