---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/18 23:29
---
-- canalSyncUserCreditScript UserCreditCacheService
local key = KEYS[1]
local userCredit
local userId
ARGV[1] = string.gsub(ARGV[1] , '("userId":)(%s*)(%d+)' , '%1"%3"')
for _ , redisCommand in pairs(cjson.decode(ARGV[1])) do
    userCredit = redisCommand['value']
    userId = userCredit['userId']
    if (redisCommand['command'] == 'INSERT' or redisCommand['command'] == 'UPDATE') then
        for index , value in pairs(userCredit) do
            if index == 'money' then
                value = string.format("%.2f" , value)
            end
            redis.call('HSET' , key .. userId , index , value)
        end
    else
        redis.call('DEL' , key .. userId)
    end
end