---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/18 23:29
---
-- canalSyncLogPaymentScript.lua PaymentCacheService
local key = KEYS[1]
local redisCommand
local logPayment
for _ , value in pairs(ARGV) do
    redisCommand = cjson.decode(value)
    logPayment = redisCommand['value']
    key = '"' .. string.gsub(key , '"' , '') .. logPayment['goodsId'] .. '"'
    if redisCommand['command'] == 'INSERT' then
        redis.call('LPUSH' , key , logPayment['payId'] .. '-' .. logPayment['operation'])
    elseif redisCommand['command'] == 'UPDATE' then
        local oldLogPayment = redisCommand['oldValue']
        if oldLogPayment['operation'] ~= nil then
            redis.call('LPUSH' , key , logPayment['payId'] .. '-' .. logPayment['operation'])
            redis.call('LREM' , key , 0 , logPayment['payId'] .. '-' .. oldLogPayment['operation'])
        end
    else
        redis.call('LREM' , key , 0 , logPayment['orderId'] .. '-' .. logPayment['operation'])
    end
end