---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/18 23:29
---
-- canalSyncPaymentScript PaymentCacheService
local key = KEYS[1]
local redisCommand
local payment
for _ , value in pairs(ARGV) do
    redisCommand = cjson.decode(value)
    payment = redisCommand['value']
    key = '"' .. string.gsub(key , '"' , '') .. payment['payId'] .. '"'
    if (redisCommand['command'] == 'INSERT' or redisCommand['command'] == 'UPDATE') then
        payment['@type'] = 'com.waibao.payment.entity.Payment'
        redis.call('SET' , key , cjson.encode(payment))
    else
        redis.call('DEL' , key)
    end
end