---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/18 23:29
---
-- canalSyncLogUserCreditScript LogUserCreditCacheService
local key = KEYS[1]
local logUserCredit
local userId
local orderId
local operation
ARGV[1] = string.gsub(ARGV[1] , '("userId":)(%s*)(%d+)' , '%1"%3"')
for _ , redisCommand in pairs(cjson.decode(ARGV[1])) do
    logUserCredit = redisCommand['value']
    userId = logUserCredit['userId']
    orderId = logUserCredit['orderId']
    operation = logUserCredit['operation']
    redis.call('SADD' , key , userId .. orderId .. '-' .. operation)
end