---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/18 23:29
---
-- canalSyncPaymentScript PaymentCacheService
local key = KEYS[1]
local payment
local payId
ARGV[1] = string.gsub(ARGV[1] , '("id":)(%s*)(%d+)' , '%1"%3"')
ARGV[1] = string.gsub(ARGV[1] , '("userId":)(%s*)(%d+)' , '%1"%3"')
for _ , redisCommand in pairs(cjson.decode(ARGV[1])) do
    payment = redisCommand['value']
    payId = payment['payId']
    if (redisCommand['command'] == 'INSERT' or redisCommand['command'] == 'UPDATE') then
        for index , value in pairs(payment) do
            redis.call('HSET' , key .. payId , index , value)
        end
    else
        redis.call('DEL' , key .. payId)
    end
end