---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/18 23:37
---
-- checkLogPaymentOperationScript LogPaymentCacheService
local key = KEYS[1]
local count = tonumber(redis.call('LREM' , key .. ARGV[1] , 0 , ARGV[2] .. '-' .. ARGV[2]))
if count > 0 then
    redis.call('LPUSH' , key .. ARGV[1] , ARGV[2] .. '-' .. ARGV[3])
    return true
else
    return false
end