server:
  port: 8001

logging:
  level:
    root: info

spring:
  application:
    name: waibao-user

  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://10.60.64.66:33306/waibao?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://10.60.64.66:33307/waibao?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001
    rules:
      readwrite-splitting:
        data-sources:
          ds0:
            type: Static
            props:
              write-data-source-name: master
              read-data-source-names: slave
  redis:
    host: 10.60.64.66
    database: 2
    password: wssy001
    timeout: 1000
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
  cloud:
    nacos:
      server-addr: 10.60.64.66:8848
      discovery:
        namespace: waibao
      username: nacos
      password: nacos

      config:
        namespace: waibao
        extension-configs: application.properties,${spring.application.name}.properties