---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 09:17
---
-- batchInsertUserExtraScript UserExtraCacheService
local key = KEYS[1]
local userId
if not (string.find(ARGV[1] , '"userId"') == nil) then
    ARGV[1] = string.gsub(ARGV[1] , '("userId":)(%d+)' , '%1"%2"')
end
for _ , userExtra in pairs(cjson.decode(ARGV[1])) do
    userId = userExtra['userId']
    for index , value in pairs(userExtra) do
        redis.call('HSET' , key .. userId , index , tostring(value))
    end
end