---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 09:17
---
-- batchInsertUserExtraScript UserExtraCacheService
local key = KEYS[1]
local userExtra
local userId
for _ , userExtraData in pairs(ARGV) do
    userExtra = cjson.decode(userExtraData)
    userId = userExtra['userId']
    redis.call('HSET' , key .. userId , '@type' , 'com.waibao.user.entity.UserExtra')
    for index , value in pairs(userExtra) do
        redis.call('HSET' , key .. userId , index , value)
    end
end