---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 08:35
---
-- batchInsertUserScript UserCacheService
local key = KEYS[1]
local user
local userId
for _ , userdata in ipairs(ARGV) do
    user = cjson.decode(userdata)
    userId = user['id']
    redis.call('HSET' , key .. userId , '@type' , 'com.waibao.user.entity.User')
    for index , value in pairs(user) do
        redis.call('HSET' , key .. userId , index , value)
    end
end