---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 09:13
---
-- getAdminScript AdminCacheService
local admin = {}
local key = KEYS[1]
local adminId = ARGV[1]
local adminKeys = redis.call('HVALS' , key .. adminId)
for _ , value in pairs(adminKeys) do
    admin[value] = redis.call('HGET' , key .. adminId , value)
end

return cjson.encode(admin)