---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 08:57
---
-- getUserScript UserCacheService
local user = {}
local key = KEYS[1]
local userId = ARGV[1]
local userKeys = redis.call('HVALS', key .. userId)
for _, value in pairs(userKeys) do
    user[value] = redis.call('HGET', key .. userId, value)
end

return cjson.encode(user)