---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 08:57
---
-- insertUserScript UserCacheService
local key = KEYS[1]
ARGV[1] = string.gsub(ARGV[1] , '("id":)(%d+)' , '%1"%2"')
local user = cjson.decode(ARGV[1])
local userId = user['id']
for index , value in pairs(user) do
    redis.call('HSET' , key .. userId , index , tostring(value))
end