---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 09:21
---
--insertUserExtraScript UserExtraCacheService
local key = KEYS[1]
local userExtra = cjson.decode(value)
local userId = userExtra['userId']
redis.call('HSET' , key .. userId , '@type' , 'com.waibao.user.entity.UserExtra')
for index , value in pairs(userExtra) do
    redis.call('HSET' , key .. userId , index , value)
end