---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 09:14
---
-- insertAdminScript AdminCacheService
local key = KEYS[1]
local admin = cjson.decode(ARGV[1])
local adminId = admin['id']
redis.call('HSET' , key .. adminId , '@type' , 'com.waibao.user.entity.Admin')
for index , value in pairs(admin) do
    redis.call('HSET' , key .. adminId , index , value)
end