---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 09:21
---
--insertUserExtraScript UserExtraCacheService
local key = KEYS[1]
if not (string.find(ARGV[1] , '"userId"') == nil) then
    ARGV[1] = string.gsub(ARGV[1] , '("userId":)(%s*)(%d+)' , '%1"%3"')
end
local userExtra = cjson.decode(ARGV[1])
local userId = userExtra['userId'] .. ''
for index , value in pairs(userExtra) do
    redis.call('HSET' , key .. userId , index , tostring(value))
end