---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 08:57
---
-- insertUserScript UserCacheService
local key = KEYS[1]
local user = cjson.decode(ARGV[1])
local userId = user['id']
redis.call('HSET' , key .. userId , '@type' , 'com.waibao.user.entity.User')
for index , value in pairs(user) do
    redis.call('HSET' , key .. userId , index , value)
end