# server
server:
  port: 9527
# application
spring:
  redis:
    host: 10.60.64.66
    database: 2
    password: wssy001
    timeout: 1000
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10

  main:
    web-application-type: reactive

  application:
    name: waibao-gateway
  # profile
  #  profiles:
  #    active: dev
  # nacos
  cloud:
    nacos:
      server-addr: 10.60.64.66:8848
      username: nacos
      password: nacos
      discovery:
        namespace: waibao
      config:
        namespace: waibao
        extension-configs: application.properties,${spring.application.name}.properties

    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: waibao-user #payment_routh    #路由的ID，没有固定规则但要求唯一，简易配合服务名
          #          uri: http://localhost:8001         #匹配后提供服务的路由地址
          uri: lb://waibao-user   #匹配后提供服务的路由地址，lb后跟提供服务的微服务的名，不要写错
          predicates:
            - Path=/**          #断言，路径相匹配的进行路由
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE