---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 18:07
---
-- batchUpdateOrderGoodsScript OrderGoodsCacheService
local key = KEYS[1]
local orderGoodsList = {}
local orderGoods
for _ , value in pairs(ARGV) do
    orderGoods = cjson.decode(value)
    local count = tonumber(redis.call('DEL' , key .. orderGoods["orderId"]))
    if count == 0 then
        table.insert(orderGoodsList , orderGoods)
    else
        orderGoods['@type'] = 'com.waibao.order.entity.OrderUser'
        redis.call('SET' , key .. orderGoods["orderId"] , cjson.encode(orderGoods))
    end
end

return cjson.encode(orderGoodsList)