---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 17:33
---
-- batchDeleteOrderRetailerScript OrderRetailerCacheService
local key = KEYS[1]
local orderRetailerList = {}
for _ , value in pairs(ARGV) do
    local orderRetailer = cjson.decode(value)
    local count = tonumber(redis.call('SREM' , key .. orderRetailer["retailerId"] , orderRetailer["orderId"]))
    if count == 0 then
        table.insert(orderRetailerList , orderRetailer)
    end
end

return cjson.encode(orderRetailerList)