---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 17:30
---
-- batchDeleteOrderUserScript OrderUserCacheService
local key = KEYS[1]
local orderUserList = {}
local orderUser
for _ , value in pairs(ARGV) do
    orderUser = cjson.decode(value)
    local count = tonumber(redis.call('SREM' , key .. orderUser["userId"] , orderUser["orderId"]))
    if count == 0 then
        table.insert(orderUserList , orderUser)
    end
end

return cjson.encode(orderUserList)