---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 17:29
---
-- batchInsertOrderUserScript OrderUserCacheService
local key = KEYS[1]
local orderUserList = {}
local orderUser
for _ , value in pairs(ARGV) do
    orderUser = cjson.decode(value)
    orderUser['@type'] = 'com.waibao.order.entity.OrderUser'
    local count = tonumber(redis.call('SETNX' , key .. orderUser["userId"] , cjson.encode(orderUser)))
    if count == 0 then
        table.insert(orderUserList , orderUser)
    end
end

return cjson.encode(orderUserList)