---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 17:32
---
-- batchInsertOrderRetailerScript OrderRetailerCacheService
local key = KEYS[1]
local orderRetailerList = {}
local orderRetailer
for _ , value in pairs(ARGV) do
    orderRetailer = cjson.decode(value)
    orderRetailer['@type'] = 'com.waibao.order.entity.OrderRetailer'
    local count = tonumber(redis.call('SETNX' , key .. orderRetailer["retailerId"] , cjson.encode(orderRetailer)))
    if count == 0 then
        table.insert(orderRetailerList , orderRetailer)
    end
end

return cjson.encode(orderRetailerList)