---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 17:34
---
-- batchInsertOrderGoodsScript OrderGoodsCacheService
local key = KEYS[1]
local orderGoodsList = {}
local orderGoods
for _ , value in pairs(ARGV) do
    orderGoods = cjson.decode(value)
    orderGoods['@type'] = 'com.waibao.order.entity.OrderUser'
    local count = tonumber(redis.call('SETNX' , key .. orderGoods["orderId"] , cjson.encode(orderGoods)))
    if count == 0 then
        table.insert(orderGoodsList , orderGoods)
    end
end

return cjson.encode(orderGoodsList)