---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 17:29
---
-- batchInsertOrderUserScript OrderUserCacheService
local key = KEYS[1]
local orderUserList = {}
for _ , value in pairs(ARGV) do
    local orderUser = cjson.decode(value)
    local count = tonumber(redis.call('SETNX' , key .. orderUser["userId"] , orderUser["orderId"]))
    if count == 0 then
        table.insert(orderUserList , orderUser)
    end
end

return cjson.encode(orderUserList)