---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 17:31
---
-- canalSyncOrderUserScript OrderUserCacheService
local key = KEYS[1]
local redisCommand
local orderUser
for _ , value in pairs(ARGV) do
    redisCommand = cjson.decode(value)
    orderUser = redisCommand['value']
    key = '"' .. string.gsub(key , '"' , '') .. orderUser['orderId'] .. '"'
    if (redisCommand['command'] == 'INSERT' or redisCommand['command'] == 'UPDATE') then
        orderUser['@type'] = 'com.waibao.order.entity.OrderUser'
        redis.call('SET' , key , cjson.encode(orderUser))
    else
        redis.call('DEL' , key)
    end
end