---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 18:10
---
-- canalSyncOrderGoodsScript OrderGoodsCacheService
local key = KEYS[1]
for _ , value in pairs(ARGV) do
    local redisCommand = cjson.decode(value)
    local orderVO = redisCommand['value']
    key = '"' .. string.gsub(key, '"', '') .. orderVO['orderId'] .. '"'
    if redisCommand['command'] == 'SET' then
        orderVO['@type'] = 'com.waibao.util.vo.order.OrderVO'
        redis.call('SET', key, cjson.encode(orderVO))
    else
        redis.call('DEL', key)
    end
end