---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 17:33
---
-- canalSyncOrderRetailerScript OrderRetailerCacheService
local key = KEYS[1]
for _ , value in pairs(ARGV) do
    local redisCommand = cjson.decode(value)
    local orderRetailer = redisCommand['value']
    key = '"' .. string.gsub(key, '"', '') .. orderRetailer['retailerId'] .. '"'
    if redisCommand['command'] == 'SET' then
        orderRetailer['@type'] = 'com.waibao.order.entity.OrderRetailer'
        redis.call('SET', key, cjson.encode(orderRetailer))
    else
        redis.call('DEL', key)
    end
end