---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 18:13
---
-- canalSyncLogOrderUserScript LogOrderUserCacheService
local key
local logOrderUser
ARGV[1] = string.gsub(ARGV[1] , '("userId":)(%s*)(%d+)' , '%1"%3"')
for _ , redisCommand in pairs(cjson.decode(ARGV[1])) do
    logOrderUser = redisCommand['value']
    key = KEYS[1] .. logOrderUser['userId']
    if redisCommand['command'] == 'INSERT' then
        redis.call('LPUSH' , key , logOrderUser['orderId'] .. '-' .. logOrderUser['operation'])
    elseif redisCommand['command'] == 'UPDATE' then
        local oldLogOrderUser = redisCommand['oldValue']
        if oldLogOrderUser['operation'] ~= nil then
            redis.call('LPUSH' , key , logOrderUser['orderId'] .. '-' .. logOrderUser['operation'])
            redis.call('LREM' , key , 0 , logOrderUser['orderId'] .. '-' .. oldLogOrderUser['operation'])
        end
    else
        redis.call('LREM' , key , 0 , logOrderUser['orderId'] .. '-' .. logOrderUser['operation'])
    end
end