---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 18:13
---
-- canalSyncLogOrderUserScript LogOrderUserCacheService
local key = KEYS[1]
for _ , value in pairs(ARGV) do
    local redisCommand = cjson.decode(value)
    local logOrderUser = redisCommand['value']
    key = '"' .. string.gsub(key, '"', '') .. logOrderUser['userId'] .. '"'
    local command = redisCommand['command']
    if command == 'INSERT' then
        redis.call('LPUSH', key, logOrderUser['orderId'] .. '-' .. logOrderUser['operation'])
    elseif command == 'UPDATE' then
        local oldLogOrderUser = redisCommand['oldValue']
        if oldLogOrderUser['operation'] ~= nil then
            redis.call('LPUSH', key, logOrderUser['orderId'] .. '-' .. logOrderUser['operation'])
            redis.call('LREM', key, 0, logOrderUser['orderId'] .. '-' .. oldLogOrderUser['operation'])
        end
    else
        redis.call('LREM', key, 0, logOrderUser['orderId'] .. '-' .. logOrderUser['operation'])
    end
end