---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by alexpetertyler.
--- DateTime: 2022/3/16 17:33
---
-- canalSyncOrderRetailerScript OrderRetailerCacheService
local key = KEYS[1]
local redisCommand
local orderRetailer
for _ , value in pairs(ARGV) do
    redisCommand = cjson.decode(value)
    orderRetailer = redisCommand['value']
    key = '"' .. string.gsub(key , '"' , '') .. orderRetailer['orderId'] .. '"'
    if (redisCommand['command'] == 'INSERT' or redisCommand['command'] == 'UPDATE') then
        orderRetailer['@type'] = 'com.waibao.order.entity.OrderRetailer'
        redis.call('SET' , key , cjson.encode(orderRetailer))
    else
        redis.call('DEL' , key)
    end
end