spring:
  application:
    name: seckill-provider

  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://10.60.64.66:33306/waibao?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://10.60.64.66:33307/waibao?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001
    rules:
      readwrite-splitting:
        data-sources:
          ds0:
            type: Static
            props:
              write-data-source-name: master
              read-data-source-names: slave

  redis:
    host: 10.60.64.66
    database: 2
    password: wssy001
    timeout: 1000
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10

  task:
    execution:
      pool:
        max-size: 16
        keep-alive: "10s"
      thread-name-prefix: 异步任务-
    scheduling:
      pool:
        size: 5
      thread-name-prefix: 定时任务-

rocketmq:
  name-server: 10.60.64.66:39876
  producer:
    group: seckill
aj:
  captcha:
    cache-type: redis
    interference-options: 2
    type: blockpuzzle