server:
  port: 8005
logging:
  level:
    root: info

spring:
  application:
    name: waibao-payment

  shardingsphere:
    datasource:
      names: master,slave,master-credit-user,master-payment,slave-credit-user,slave-payment
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://10.60.64.66:33306/waibao_v2?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://10.60.64.66:33307/waibao_v2?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001
      master-credit-user:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://10.60.64.66:33306/waibao_credit_user?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001
      master-payment:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://10.60.64.66:33306/waibao_payment?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001
      slave-credit-user:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://10.60.64.66:33307/waibao_credit_user?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001
      slave-payment:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://10.60.64.66:33307/waibao_payment?useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
        username: root
        password: wssy001

    sharding:
      tables:
        admin:
          actualDataNodes: master.admin
        seckill_goods:
          actualDataNodes: master.seckill_goods
        order_user:
          actualDataNodes: master-credit-user.user_credit_$->{0..1}
          tableStrategy:
            inline:
              shardingColumn: user_id
              algorithmExpression: user_credit_$->{user_id % 2}
        order_retailer:
          actualDataNodes: master-payment.payment_$->{0..1}
          tableStrategy:
            inline:
              shardingColumn: pay_id
              algorithmExpression: payment_$->{pay_id % 2}

      master-slave-rules:
        master:
          master-data-source-name: master
          SlaveDataSourceNames: slave
        master-order-user:
          master-data-source-name: master-credit-user
          SlaveDataSourceNames: slave-credit-user
        master-order-retailer:
          master-data-source-name: master-payment
          SlaveDataSourceNames: slave-payment

  redis:
    host: 10.60.64.66
    database: 2
    password: wssy001
    timeout: 1000
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
  cloud:
    nacos:
      server-addr: 10.60.64.66:8848
      discovery:
        namespace: waibao
      username: nacos
      password: nacos

      config:
        namespace: waibao
        extension-configs: application.properties,${spring.application.name}.properties